<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OrgMemberSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('org_members')->insert([
            // 1) operations: คณะที่ปรึกษา
            [
                'name' => 'ดร. สมยศ วงศ์อนุรักษ์',
                'position' => 'ที่ปรึกษาศูนย์พัฒนาครูและบุคลากรทางการศึกษา สพป.ชุมพร เขต 1',
                'photo' => null,
                'role' => 'advisor',
                'committee' => 'operations',
                'role_title' => 'ที่ปรึกษาศูนย์พัฒนาครูและบุคลากรทางการศึกษา',
                'level' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นายสมเกียรติ มณีรัตน์',
                'position' => 'ผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'operations',
                'role_title' => 'ประธานคณะกรรมการฝ่ายบริหารศูนย์',
                'level' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวกัลยา สุขจิตต์',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'operations',
                'role_title' => 'รองประธานคณะกรรมการฝ่ายวิชาการ',
                'level' => 2,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นายธีรวัฒน์ จันทร์แก้ว',
                'position' => 'ครูวิทยากรแกนนำวิทย์',
                'photo' => null,
                'role' => 'member',
                'committee' => 'operations',
                'role_title' => 'กรรมการและเลขานุการศูนย์',
                'level' => 2,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางศิริพร บุญรอด',
                'position' => 'ครูวิทยากรแกนนำเทคโนโลยี',
                'photo' => null,
                'role' => 'member',
                'committee' => 'operations',
                'role_title' => 'กรรมการและผู้ช่วยเลขานุการ',
                'level' => 3,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 2) executive: คณะกรรมการอำนวยการประจำศูนย์ฯ (Executive Board)
            [
                'name' => 'นางสาวเสาวนีย์ ช่วยอนันต์',
                'position' => 'ผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'ประธานศูนย์พัฒนาครูและบุคลากรทางการศึกษา สพป.ชุมพร เขต 1',
                'level' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นายกิตติพงษ์ น้อยจีน',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'รองประธานศูนย์พัฒนาครูและบุคลากรทางการศึกษา สพป.ชุมพร เขต 1',
                'level' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางอัญชลี ศรีสงคราม',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'คณะกรรมการอำนวยการ',
                'level' => 3,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวกัญชพร บุญชัย',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'คณะกรรมการอำนวยการ',
                'level' => 3,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางนาตยา พงษ์ศิริกุล',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร (วิทยฐานะชำนาญการพิเศษ)',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'ผู้ประสานงานศูนย์พัฒนาครูฯ / กรรมการและเลขานุการ',
                'level' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวสุนิศา อินทรมงคล',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'executive',
                'role_title' => 'ผู้ประสานงานศูนย์พัฒนาครูฯ / กรรมการและผู้ช่วยเลขานุการ',
                'level' => 4,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 3) academic: คณะกรรมการฝ่ายการดำเนินงานและวิชาการ (Academic & Operations Committee)
            [
                'name' => 'นายกิตติพงษ์ น้อยจีน',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'ประธานกรรมการดำเนินงาน',
                'level' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวกัญชพร บุญชัย',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'รองประธานกรรมการดำเนินงาน',
                'level' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางดวงพร จินดาชื่น',
                'position' => 'หัวหน้ากลุ่มสาระวิทยาศาสตร์และเทคโนโลยี / ครู',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'กรรมการฝ่ายวิชาการ',
                'level' => 3,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวปัญจพร ยงสุนิจ',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'กรรมการฝ่ายดำเนินงาน',
                'level' => 3,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นายไพฑูรย์ อุ่นอบ',
                'position' => 'ครูผู้สอนวิทยาศาสตร์ ป.5',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'กรรมการฝ่ายดำเนินงาน',
                'level' => 3,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางนาตยา พงษ์ศิริกุล',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'กรรมการและเลขานุการ',
                'level' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวสุนิศา อินทรมงคล',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'academic',
                'role_title' => 'กรรมการและผู้ช่วยเลขานุการ',
                'level' => 4,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // 4) finance: คณะกรรมการฝ่ายการเงิน พัสดุ และสถานที่ (Finance & Venue Committee)
            [
                'name' => 'นางอัญชลี ศรีสงคราม',
                'position' => 'รองผู้อำนวยการโรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'ประธานกรรมการสถานที่ / รอง ผอ.',
                'level' => 1,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวปรีดาพร อินทสุภา',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'รองประธานกรรมการสถานที่ / ครู',
                'level' => 2,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางชาติลภา กิมเซียะ',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'รองประธานกรรมการการเงินและพัสดุ / ครู',
                'level' => 2,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวภาณุมาศ นวลปลื้ม',
                'position' => 'นักวิชาการเงินและบัญชี',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการการเงิน',
                'level' => 3,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวกฤติลักษณ์ ชุมแสง',
                'position' => 'ครูผู้สอนคณิตศาสตร์ ป.4',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการสถานที่',
                'level' => 3,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวชุติกาญจน์ สร้อยนวม',
                'position' => 'ครูผู้ช่วย',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการสถานที่',
                'level' => 3,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวสิริพร สังข์มรรทร',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการและผู้ช่วยเลขานุการฝ่ายการเงิน / ครู',
                'level' => 4,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นางสาวอรชร พรหมภินันท์',
                'position' => 'ครู โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการและเลขานุการฝ่ายสถานที่ / ครู',
                'level' => 4,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'นายธราธิป หทัยวิวัฒน์กุล',
                'position' => 'ครูอัตราจ้าง โรงเรียนอนุบาลชุมพร',
                'photo' => null,
                'role' => 'member',
                'committee' => 'finance',
                'role_title' => 'กรรมการและผู้ช่วยเลขานุการฝ่ายสถานที่ / ครูอัตราจ้าง',
                'level' => 4,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
